version: '3.8'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - mariadb-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8084:80"
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
    networks:
      - mariadb-network

networks:
  mariadb-network:
    driver: bridge
