pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/marcobarem/DevOps-Jenkins.git'
            }
        }
        stage('Clean Up') {
            steps {
                script {
                    sh 'docker rm -f postgres || true'
                    sh 'docker rm -f pgadmin || true'
                    sh 'docker network prune -f || true'
                }
            }
        }
        stage('Build') {
            steps {
                dir('postgres-dpage/pgadmin4') {
                    sh 'docker-compose down'
                    sh 'docker-compose build'
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('postgres-dpage/pgadmin4') {
                    sh 'docker-compose up -d'
                }
            }
        }
    }
}
